export default {
    queryDropdown: '/dropdown',
    queryPosition: '/position/search',
    positionProcessCount: '/position/process_count',
    positionQueryList: '/position/query_list',
    positionAdd: '/position/add',
    positionDelete: '/position/delete',
    candidateProcessCount: '/candidate/process_count',
    candidateSearch: '/candidate/search',
    candidateProcessChange: '/candidate/process_change',
    candidateAdd: '/candidate/add',
    candidateAddRemark: '/candidate/add_remark',
    candidateDelete: '/candidate/delete',
    CALANDAR_INTERVIEW: '/calendar/process_init_interview',
    CALANDAR_EXAM: '/calendar/process_init_exam',
    CALANDAR_IN: '/calendar/process_init_in',
    calendarAdd: '/calendar/add',
    calendarDelete: '/calendar/delete',
    login: `/login`,
    logout: `/logout`,
}
