export default {
    queryDropdown: '/dropdown',
    queryPosition: '/position/search',
    positionQueryList: '/position/query_list',
    positionAdd: '/position/add',
    positionDelete: '/position/delete',
    candidateProcessCount: '/candidate/process_count',
    candidateSearch: '/candidate/search',
    candidateProcessChange: '/candidate/process_change',
    candidateAdd: '/candidate/add',
    candidateAddRemark: '/canditate/add_remark',
    candidateDelete: '/canditate/delete',
    calendarProcessInitInterview: '/calendar/process_init_interview',
    calendarProcessInitExam: '/calendar/process_init_exam',
    calendarProcessInitIn: '/calendar/process_init_in',
    calendarAdd: '/calendar/add',
    calendarDelete: '/calendar/delete',
    login: `/login`,
    logout: `/logout`,
}
