export default {
    resultCode: '000000',
    resultMesg: '请求成功',
    data: {
        cNumber: 13,
        rNumber: 8,
        dataSource: [{
            sex: 'M',
            isNew: 0, // 0不是新人， 1是新人
            telephoneState: 0, // 1,2,3 1离线,2通话,3空闲
            umId: 'wangdatou001',
            name: '王大头',
            x: 1,
            y: 1
        }, {
            sex: 'M',
            isNew: 1,
            telephoneState: 0,
            umId: 'wangdatou001',
            name: '王大头',
            x: 2,
            y: 1
        }, {
            sex: 'F',
            isNew: 1,
            telephoneState: 1,
            umId: 'wangdatou001',
            name: '王大头',
            x: 3,
            y: 1
        }, {
            sex: 'M',
            isNew: 0,
            telephoneState: 1,
            umId: 'wangdatou001',
            name: '王大头',
            x: 4,
            y: 1
        }, {
            sex: 'M',
            isNew: 0,
            telephoneState: 4,
            umId: 'wangdatou001',
            name: '王大头',
            x: 5,
            y: 1
        }, {
            sex: 'M',
            isNew: 0,
            telephoneState: 1,
            umId: 'wangdatou001',
            name: '王大头',
            x: 6,
            y: 1
        }, {
            sex: 'F',
            isNew: 0,
            telephoneState: 0,
            umId: 'lidatou001',
            name: '李大头',
            x: 1,
            y: 2
        }, {
            sex: 'M',
            isNew: 1,
            telephoneState: 4,
            umId: 'wangdapang001',
            name: '王大胖',
            x: 2,
            y: 2
        }, {
            sex: 'F',
            isNew: 1,
            telephoneState: 3,
            umId: 'wangxiaopang001',
            name: '王小胖',
            x: 3,
            y: 2
        }, {
            sex: 'F',
            isNew: 0,
            telephoneState: 3,
            umId: 'wangdatou001',
            name: '王大头',
            x: 4,
            y: 2
        }, {
            sex: 'M',
            isNew: 0,
            telephoneState: 4,
            umId: 'wangdatou001',
            name: '王大头',
            x: 5,
            y: 2
        }, {
            sex: 'M',
            isNew: 0,
            telephoneState: 1,
            umId: 'wangdatou001',
            name: '王大头',
            x: 6,
            y: 2
        }]
    }
}
